apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: simple-server
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: arch.homework
      http:
        paths:
          - backend:
              service:
                name: simple-server
                port:
                  number: 8000
            pathType: Prefix
            path: /